[supervisord]
nodaemon=true
user=prism
logfile=/var/log/prism/supervisord.log
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=Xvfb %(ENV_DISPLAY)s -screen 0 %(ENV_RESOLUTION)sx%(ENV_COLOR_DEPTH)s -ac -noreset
autorestart=true
priority=10
stdout_logfile=/var/log/prism/xvfb.log
stderr_logfile=/var/log/prism/xvfb_err.log

[program:openbox]
command=openbox-session
environment=DISPLAY="%(ENV_DISPLAY)s"
autorestart=true
priority=20
stdout_logfile=/var/log/prism/openbox.log
stderr_logfile=/var/log/prism/openbox_err.log

[program:x11vnc]
command=x11vnc -display %(ENV_DISPLAY)s -forever -shared -nopw -rfbport %(ENV_VNC_PORT)s -listen 0.0.0.0
autorestart=true
priority=30
stdout_logfile=/var/log/prism/x11vnc.log
stderr_logfile=/var/log/prism/x11vnc_err.log

[program:novnc]
command=websockify --web /usr/share/novnc %(ENV_WEBRTC_PORT)s localhost:%(ENV_VNC_PORT)s
autorestart=true
priority=40
stdout_logfile=/var/log/prism/novnc.log
stderr_logfile=/var/log/prism/novnc_err.log
