export const POLICY_REASON_CODES = {
    HIGH_RISK_ALLOWED_PROFILE_BYPASS: "HIGH_RISK_ALLOWED_PROFILE_BYPASS",
    HIGH_RISK_ALLOWED_WHITELIST_BYPASS: "HIGH_RISK_ALLOWED_WHITELIST_BYPASS",
    HIGH_RISK_APPROVAL_REQUIRED: "HIGH_RISK_APPROVAL_REQUIRED",
    MEDIUM_RISK_DENY_MISSING_ROLLBACK: "MEDIUM_RISK_DENY_MISSING_ROLLBACK",
    MEDIUM_RISK_WARN_MISSING_ROLLBACK: "MEDIUM_RISK_WARN_MISSING_ROLLBACK",
    MEDIUM_RISK_ALLOW_CONDITIONAL: "MEDIUM_RISK_ALLOW_CONDITIONAL",
    MEDIUM_RISK_DENY_TIER2_DISABLED: "MEDIUM_RISK_DENY_TIER2_DISABLED",
    LOW_RISK_AUDIT_LOGGED: "LOW_RISK_AUDIT_LOGGED",
    LOW_RISK_DENY_BUSINESS_MUTATION: "LOW_RISK_DENY_BUSINESS_MUTATION",
    LOW_RISK_DENY_TIER1_DISABLED: "LOW_RISK_DENY_TIER1_DISABLED",
    LOW_RISK_ALLOW_AUTONOMOUS: "LOW_RISK_ALLOW_AUTONOMOUS",
    FALLBACK_DENY_NO_RULE: "FALLBACK_DENY_NO_RULE",
} as const;

export type PolicyReasonCode = (typeof POLICY_REASON_CODES)[keyof typeof POLICY_REASON_CODES];
